name: album
description: Touch your digital album phisically.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  modal_bottom_sheet: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.3.0
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  get: ^4.6.1
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - .env